---
- name: Create Proxmox VMs
  hosts: localhost
  gather_facts: no

  vars:
    proxmox_host: "192.168.1.3"
    proxmox_user: "ansible@pve"
    proxmox_password: "your-password-here!"
    proxmox_node: "proxmox1"
    template_name: "rhel10"

    # Customization variables
    vm_base_name: "trading-app" # Base name for VMs
    vm_count: 3 # Number of VMs to create
    vm_memory: 4096 # Memory in MB
    vm_cores: 2 # CPU cores
    auto_start: true # Start VMs after creation

  tasks:
  - name: Get list of existing VMs
    community.proxmox.proxmox_vm_info:
      api_host: "{{ proxmox_host }}"
      api_user: "{{ proxmox_user }}"
      api_password: "{{ proxmox_password }}"
      validate_certs: no
      node: "{{ proxmox_node }}"
    register: vm_list

  - name: Calculate starting VMID
    set_fact:
      starting_vmid: "{{ (vm_list.proxmox_vms | map(attribute='vmid') | map('int') | max | default(99)) + 1 }}"

  - name: Display starting VMID
    debug:
      msg: "Starting VMID: {{ starting_vmid }}, creating {{ vm_count }} VMs"

  - name: Clone VMs from template
    community.proxmox.proxmox_kvm:
      api_host: "{{ proxmox_host }}"
      api_user: "{{ proxmox_user }}"
      api_password: "{{ proxmox_password }}"
      validate_certs: no

      node: "{{ proxmox_node }}"
      clone: "{{ template_name }}"
      newid: "{{ starting_vmid | int + item }}"
      name: "{{ vm_base_name }}-{{ item + 1 }}" # trading-app-1, trading-app-2, etc.
      full: yes

      timeout: 300

      memory: "{{ vm_memory }}"
      cores: "{{ vm_cores }}"

      state: present
    loop: "{{ range(0, vm_count) | list }}"
    register: cloned_vms

  - name: Start VMs
    community.proxmox.proxmox_kvm:
      api_host: "{{ proxmox_host }}"
      api_user: "{{ proxmox_user }}"
      api_password: "{{ proxmox_password }}"
      validate_certs: no
      node: "{{ proxmox_node }}"
      vmid: "{{ starting_vmid | int + item }}"
      state: started
      timeout: 60
    loop: "{{ range(0, vm_count) | list }}"
    when: auto_start

  - name: Display created VMs
    debug:
      msg: "Created VM {{ starting_vmid | int + item }}: {{ vm_base_name }}-{{ item + 1 }}"
    loop: "{{ range(0, vm_count) | list }}"
